# Use a minimal, specific Node base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Create non-root user for security
RUN addgroup -g 1001 -S appgroup && \
    adduser -S appuser -u 1001 -G appgroup

# Copy package files first (for efficient caching)
COPY package*.json ./

# Install only production dependencies
RUN npm ci  \
    chown -R appuser:appgroup /app && \
    chmod -R 755 /app

# Switch to non-root user
USER appuser

# Copy the rest of the app (source code)
COPY --chown=appuser:appgroup . .


# Run the app
CMD ["node", "server.js"]
